# -*- coding: utf-8 -*-
"""email.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ff8AOPKSq0Go9DxSFG-njSzp5oMPS44N
"""

import smtplib
import csv
from email.message import EmailMessage
from getpass import getpass
from google.colab import files

# Step 1: Upload your CSV file
uploaded = files.upload()  # Use this to upload emails.csv

# Step 2: Read the uploaded file
def read_emails_from_csv(file_name):
    with open(file_name, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        return list(reader)

# Step 3: Send email
def send_email(sender_email, password, to_address, subject, body):
    msg = EmailMessage()
    msg['From'] = sender_email
    msg['To'] = to_address
    msg['Subject'] = subject
    msg.set_content(body)

    try:
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(sender_email, password)
            server.send_message(msg)
            print(f"✅ Email sent to {to_address}")
    except Exception as e:
        print(f"❌ Failed to send email to {to_address}: {e}")

# Step 4: Main program
sender_email = input("Enter your Gmail address: ")
password = getpass("Enter your App Password (not Gmail password): ")

contacts = read_emails_from_csv('emails.csv')

for contact in contacts:
    email = contact['email']
    message = contact['message']
    send_email(sender_email, password, email, "Automated Message", message)